---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lingua-quiz-production-apps
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: lingua-quiz-production-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/production/apps
  prune: true
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
