---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lingua-quiz-cleanup
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/cleanup
  prune: true
  wait: false
  timeout: 5m
