---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: preview-environments
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: |
        [preview] Update image tags

        Automated image update for preview environments
    push:
      branch: main
  update:
    path: ./flux/clusters
    strategy: Setters
