---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: preview-pr-219-apps
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: preview-pr-219-infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/preview-pr-219/apps
  prune: true
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
