---
# Deploy staging environment in the same cluster but different namespace
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lingua-quiz-staging
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/staging
  prune: true
  wait: false
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
