apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingua-quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lingua-quiz
  template:
    metadata:
      labels:
        app: lingua-quiz
    spec:
      containers:
        - name: backend
          image: lingua-quiz:latest
          ports:
            - containerPort: PORT_PLACEHOLDER
              hostPort: PORT_PLACEHOLDER
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: PORT_PLACEHOLDER
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: PORT_PLACEHOLDER
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: PORT_PLACEHOLDER
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: PORT
              value: "PORT_PLACEHOLDER"
