apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingua-quiz-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lingua-quiz-backend
  template:
    metadata:
      labels:
        app: lingua-quiz-backend
    spec:
      containers:
        - name: backend
          image: lingua-quiz-backend
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '250m'
              memory: '256Mi'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: NODE_ENV
              value: 'production'
            - name: DB_HOST
              value: 'postgres'
            - name: DB_PORT
              value: '5432'
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: SSL_KEY_PATH
              value: '/etc/tls/tls.key'
            - name: SSL_CERT_PATH
              value: '/etc/tls/tls.crt'
            - name: PORT
              value: '3000'
          volumeMounts:
            - name: tls
              mountPath: '/etc/tls'
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: tls-secret
