apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingua-quiz-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lingua-quiz-backend
  template:
    metadata:
      labels:
        app: lingua-quiz-backend
    spec:
      containers:
      - name: backend
        image: lingua-quiz-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "linguaquiz"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET