apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: lingua-quiz
    newName: IMAGE_NAME_PLACEHOLDER
    newTag: IMAGE_TAG_PLACEHOLDER
