apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - postgres-deployment.yaml

images:
- name: lingua-quiz-backend
  newName: ${{ secrets.DOCKERHUB_USERNAME }}/lingua-quiz-backend
  newTag: latest