apiVersion: v1
kind: Service
metadata:
  name: lingua-quiz-backend-service
spec:
  selector:
    app: lingua-quiz-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer