name: 'Setup Node.js Environment'
description: 'Checks out code, sets up Node.js 24, and installs npm dependencies'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
