version: 2

updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'dependencies'
      - 'npm'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/packages/backend/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'dependencies'
      - 'python'
    groups:
      pip-dependencies:
        patterns:
          - '*'

  # Docker dependencies
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'dependencies'
      - 'docker'
    groups:
      docker-dependencies:
        patterns:
          - '*'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'dependencies'
      - 'github-actions'
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
