version: 2
updates:
  # Maintain dependencies for npm (root workspace)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"

  # Maintain dependencies for Python (backend)
  - package-ecosystem: "pip"
    directory: "/packages/backend/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"