version: 2
multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
    update-types:
      - "minor"
      - "patch"
      - "major"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "pip"
    directory: "/packages/backend/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
