version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    automerge: true # Enable auto-merge
    groups:
      all-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch", "major"]

  - package-ecosystem: "pip"
    directory: "/packages/backend/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"
    automerge: true # Enable auto-merge
    groups:
      all-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch", "major"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
    automerge: true # Enable auto-merge
    groups:
      all-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch", "major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    automerge: true # Enable auto-merge
    groups:
      all-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch", "major"]
