version: 2

updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    groups:
      npm-dev-dependencies:
        dependency-type: 'development'
      npm-prod-dependencies:
        dependency-type: 'production'

  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/packages/backend/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'

  # Docker dependencies
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
