version: 2
updates:
  # Maintain dependencies for npm (root workspace)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    # Group all npm updates together
    groups:
       all-dependencies:
         patterns:
           - "*"

  # Maintain dependencies for Python (backend)
  - package-ecosystem: "pip"
    directory: "/packages/backend/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"
    # Use the same group name to combine with other ecosystems
    groups:
       all-dependencies:
         patterns:
           - "*"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
    # Use the same group name
    groups:
       all-dependencies:
         patterns:
           - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    # Use the same group name
    groups:
       all-dependencies:
         patterns:
           - "*"
