version: 2

updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  # Pip dependencies
  - package-ecosystem: 'pip'
    directory: '/packages/backend/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      pip-dependencies:
        patterns:
          - '*'

  # Docker dependencies (single root Dockerfile)
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      docker-dependencies:
        patterns:
          - '*'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      actions-dependencies:
        patterns:
          - '*'
