apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lingua-quiz
  namespace: lingua-quiz-production
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/lingua-quiz-app
      sourceRef:
        kind: GitRepository
        name: lingua-quiz-repo
        namespace: flux-system
      interval: 1m
  values:
    registry: ghcr.io/nikolay-e/lingua-quiz
    imagePullSecrets:
      - name: ghcr-secret
    backend:
      image:
        tag: main # {"$imagepolicy": "lingua-quiz-production:backend"}
    frontend:
      image:
        tag: main # {"$imagepolicy": "lingua-quiz-production:frontend"}
  valuesFrom:
    - kind: ConfigMap
      name: lingua-quiz-values
      valuesKey: values.yaml
