apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lingua-quiz
  namespace: lingua-quiz-production
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/lingua-quiz-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - helm/lingua-quiz-app/values.yaml
        - helm/lingua-quiz-app/values.prod.yaml
  values:
    registry: ghcr.io/nikolay-e/lingua-quiz
    imagePullSecrets:
      - name: ghcr-secret
    backend:
      image:
        tag: main-08eef9a-1761388093 # {"$imagepolicy": "lingua-quiz-production:backend"}
    frontend:
      image:
        tag: main-08eef9a-1761388095 # {"$imagepolicy": "lingua-quiz-production:frontend"}
  valuesFrom:
    - kind: Secret
      name: lingua-quiz-sops-values
      valuesKey: values.yaml
