apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: backend
  namespace: lingua-quiz-production
spec:
  imageRepositoryRef:
    name: backend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
