apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: lingua-quiz-staging
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^pr-[0-9]+-[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
