creation_rules:
  # Helm values encryption
  - path_regex: helm/.*/values\.sops\.yaml$
    age: age15n3fvp4rrp7r2ugkalzrad9u3h6y68c03kr8s7k74a8za48dfqcsaprfuw # pragma: allowlist secret

  # FluxCD secrets encryption
  - path_regex: flux/clusters/.*/.*-encrypted\.yaml$
    age: age15n3fvp4rrp7r2ugkalzrad9u3h6y68c03kr8s7k74a8za48dfqcsaprfuw # pragma: allowlist secret
