apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lingua-quiz
  namespace: preview-pr-215
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/lingua-quiz-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - helm/lingua-quiz-app/values.yaml
        - helm/lingua-quiz-app/values.preview-pr-215.yaml
  values:
    registry: ghcr.io/nikolay-e/lingua-quiz
    imagePullSecrets:
      - name: ghcr-secret
    backend:
      image:
        tag: pr-215-fb6878a-1761409704 # {"$imagepolicy": "preview-pr-215:backend"}
    frontend:
      image:
        tag: pr-215-fb6878a-1761409707 # {"$imagepolicy": "preview-pr-215:frontend"}
  valuesFrom:
    - kind: Secret
      name: lingua-quiz-sops-values
      valuesKey: values.yaml
