export const AUDIO = {
  SAMPLE_RATE: 16000,
  CHANNELS: 1,
  FFT_SIZE: 2048,
  TIMESLICE_MS: 100,
} as const;

export const SCORING = {
  DEFAULT_THRESHOLD: 85,
  EXCELLENT_THRESHOLD: 95,
  GOOD_THRESHOLD: 85,
  PHONEME_ERROR_THRESHOLD: 85,
  HIGHLIGHT_THRESHOLD: 80,
  MISPRONUNCIATION_THRESHOLD: 60,
  COLOR_GREEN_THRESHOLD: 90,
  COLOR_YELLOW_THRESHOLD: 70,
} as const;

export const SIMULATION = {
  WORD_SCORE_MIN: 70,
  WORD_SCORE_RANGE: 30,
  PHONEME_SCORE_MIN: 60,
  PHONEME_SCORE_RANGE: 40,
  COMPLETENESS_MIN: 95,
  COMPLETENESS_RANGE: 5,
  PHONEME_ERROR_THRESHOLD: 70,
} as const;

export const STORAGE_KEY = 'lingua-quiz-speak';
