##
## LinguaQuiz – Copyright © 2025 Nikolay Eremeev
##
## Dual-licensed:
##  – Non-Commercial Source-Available v2  →  see LICENSE-NONCOMMERCIAL.md
##  – Commercial License v2              →  see LICENSE-COMMERCIAL.md
##
## Contact: lingua-quiz@nikolay-eremeev.com
## Repository: https://github.com/nikolay-e/lingua-quiz
##

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingua-quiz-backup.fullname" . }}-spaces-credentials
  labels:
    {{- include "lingua-quiz-backup.labels" . | nindent 4 }}
type: Opaque
data:
  # Values must be provided via --set spaces.accessKeyId and spaces.secretKey
  SPACES_ACCESS_KEY_ID: {{ .Values.spaces.accessKeyId | b64enc | quote }}
  SPACES_SECRET_KEY: {{ .Values.spaces.secretKey | b64enc | quote }}
