namespace: lingua-quiz-production

backend:
  image:
    repository: ghcr.io/nikolay-e/lingua-quiz/lingua-quiz-backend # Will be overridden by CI
    pullPolicy: Always
    tag: 'latest'
  port: 9000
  corsAllowedOrigins: 'https://lingua-quiz.nikolay-eremeev.com'
  service:
    type: ClusterIP
    port: 9000
  resources:
    limits:
      cpu: '500m'
      memory: '1Gi'
    requests:
      cpu: '100m'
      memory: '512Mi'

frontend:
  image:
    repository: ghcr.io/nikolay-e/lingua-quiz/lingua-quiz-frontend # Will be overridden by CI
    pullPolicy: Always
    tag: 'latest'
  port: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: '100m'
      memory: '512Mi'
    requests:
      cpu: '25m'
      memory: '256Mi'

# PostgreSQL configuration - use shared instance
postgres:
  enabled: false # Don't deploy PostgreSQL with the app
  external:
    host: 'shared-postgres.shared-database.svc.cluster.local'
    port: 5432
    database: 'linguaquiz'

ingress:
  enabled: true
  className: 'traefik'
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    traefik.ingress.kubernetes.io/router.entrypoints: 'web,websecure'
    traefik.ingress.kubernetes.io/router.tls: 'true'
  frontend:
    host: lingua-quiz.nikolay-eremeev.com
  backend:
    host: # Same host as frontend - API will be served from /api path
  tls:
    enabled: true
    secretName: lingua-quiz-tls  # pragma: allowlist secret

migrations:
  enabled: true
  command: ['python', 'migrate.py']
  ttlSecondsAfterFinished: 600
  restartPolicy: OnFailure
  backoffLimit: 3
  resources:
    limits:
      cpu: '200m'
      memory: '512Mi'
    requests:
      cpu: '50m'
      memory: '128Mi'

tests:
  enabled: true
  image:
    repository: ghcr.io/nikolay-e/lingua-quiz/lingua-quiz-integration-e2e-tests # Will be overridden by CI
    pullPolicy: Always
    tag: 'latest'
  ttlSecondsAfterFinished: 600
  restartPolicy: Never
  backoffLimit: 3
  skipTtsTests: 'true'
  resources:
    limits:
      cpu: '500m'
      memory: '512Mi'
    requests:
      cpu: '100m'
      memory: '256Mi'
