namespace: lingua-quiz-local

backend:
  image:
    repository: lingua-quiz-backend
    pullPolicy: Never # Use locally built image
    tag: 'local'
  port: 9000
  corsAllowedOrigins: 'http://localhost:8080,http://localhost:5173,http://localhost:30080'
  service:
    type: NodePort
    port: 9000
    nodePort: 30900
  resources:
    limits:
      cpu: '500m'
      memory: '1Gi'
    requests:
      cpu: '100m'
      memory: '512Mi'

frontend:
  image:
    repository: lingua-quiz-frontend
    pullPolicy: Never # Use locally built image
    tag: 'local'
  port: 80
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources:
    limits:
      cpu: '100m'
      memory: '512Mi'
    requests:
      cpu: '50m'
      memory: '128Mi'

# PostgreSQL configuration - use shared instance
postgres:
  enabled: false # Don't deploy PostgreSQL with the app
  external:
    host: 'shared-postgres.shared-database.svc.cluster.local'
    port: 5432
    database: 'linguaquiz_dev'
    existingSecret: 'shared-postgres-linguaquiz'

# Ingress disabled for local development (using NodePort instead)
ingress:
  enabled: false

# Local development secrets
secrets:
  jwtSecret: 'local-development-jwt-secret-change-in-production'
  googleCloudCredentialsB64: '' # Optional for local dev

# Migration configuration
migrations:
  enabled: true
  command: ['python', 'migrate.py']
  ttlSecondsAfterFinished: 300
  restartPolicy: OnFailure
  backoffLimit: 1
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '50m'
      memory: '128Mi'
  env:
    - name: DOCKER_ENVIRONMENT
      value: 'true'

# Test configuration for local development
tests:
  enabled: true
  image:
    repository: lingua-quiz-tests # Test runner image
    pullPolicy: Never
    tag: 'local'
  ttlSecondsAfterFinished: 300 # Keep job for 5 minutes after completion
  restartPolicy: Never
  backoffLimit: 2 # Retry tests up to 2 times
  skipTtsTests: 'true'
  resources:
    limits:
      cpu: '500m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
