# Default values for lingua-quiz-app chart.
# This is a YAML-formatted file.
# These are common values shared across all environments.
# Environment-specific overrides are in values.{env}.yaml files.

# Namespace - will be overridden by environment-specific values
namespace: ''

replicaCount: 1

# Backend configuration
backend:
  image:
    repository: '' # Set via CI/CD --set flags during deployment
    pullPolicy: Always
    tag: 'latest'
  replicaCount: 1
  port: 9000
  corsAllowedOrigins: '' # Set by environment-specific values files
  service:
    type: ClusterIP
    port: 9000
    # nodePort: 30900 # Optional: specify for NodePort type (used in local dev)
  resources:
    limits:
      cpu: '200m'
      memory: '512Mi'
    requests:
      cpu: '100m'
      memory: '256Mi'
  # Liveness, Readiness, Startup probes configuration
  probes:
    liveness:
      path: /api/health
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      path: /api/health
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    startup:
      path: /api/health
      failureThreshold: 30
      periodSeconds: 10
      timeoutSeconds: 5

# Frontend configuration
frontend:
  image:
    repository: '' # Set via CI/CD --set flags during deployment
    pullPolicy: Always
    tag: 'latest'
  replicaCount: 1
  port: 80 # The port Nginx listens on inside the container
  service:
    type: ClusterIP
    port: 80
    # nodePort: 30080 # Optional: specify for NodePort type (used in local dev)
  resources:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '50m'
      memory: '64Mi'
  # Liveness, Readiness probe configuration
  probes:
    liveness:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3

# PostgreSQL configuration
postgres:
  # Set to false to use external PostgreSQL database
  enabled: false # Changed: Use external shared PostgreSQL

  # External PostgreSQL configuration (when enabled: false)
  external:
    host: 'shared-postgres.shared-database.svc.cluster.local'
    port: 5432
    database: '' # Set by environment-specific values files
    existingSecret: '' # Name of existing secret with database credentials


# Ingress configuration for external access
ingress:
  enabled: true
  className: 'traefik' # Using Traefik ingress controller
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    traefik.ingress.kubernetes.io/router.entrypoints: 'web,websecure'
    traefik.ingress.kubernetes.io/router.tls: 'true'
  frontend:
    host: lingua-quiz.nikolay-eremeev.com # Set via CI/CD --set flags during deployment
  backend:
    host: # Empty for same-host deployment (API served from /api path)
  tls:
    enabled: true
    secretName: lingua-quiz-tls # Name of the K8s secret holding the cert/key

# Secrets - These MUST be provided during deployment (e.g., via --set or a secrets file)
secrets:
  jwtSecret: ''
  googleCloudCredentialsB64: ''

# Service Account configuration
serviceAccount:
  # Set to true to create a specific service account
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # If create is false, it defaults to 'default' within the helper.
  name: ''
# Database migrations configuration
migrations:
  enabled: true
  command: ['python', 'migrate.py']
  # Keep failed migration pods for 1 hour for debugging (was 120 seconds)
  ttlSecondsAfterFinished: 3600
  restartPolicy: OnFailure
  backoffLimit: 4
  resources:
    limits:
      cpu: '200m'
      memory: '512Mi'
    requests:
      cpu: '25m'
      memory: '64Mi'
  # Additional environment variables for migrations if needed
  env:
    - name: NODE_ENV
      value: 'production'
# Test configuration
tests:
  enabled: false # Disabled by default, enabled in environments that need it
  image:
    repository: '' # Set via CI/CD --set flags during deployment
    pullPolicy: Always
    tag: 'latest'
  ttlSecondsAfterFinished: 300 # Keep job for 5 minutes after completion
  restartPolicy: Never
  backoffLimit: 2 # Retry tests up to 2 times
  skipTtsTests: 'true' # Skip TTS tests by default
  resources:
    limits:
      cpu: '500m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  env: [] # Additional environment variables for tests

# Note: Database backup is now handled by the shared-postgres chart
# Optional configurations
imagePullSecrets:
  - name: ghcr-secret
# nameOverride: ""
# fullnameOverride: ""
# podSecurityContext: {}
# securityContext: {}
# nodeSelector: {}
# tolerations: []
# affinity: {}
