# generated by datamodel-codegen:
#   filename:  content_version.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class ContentVersionResponse(BaseModel):
    versionId: int = Field(..., title="Versionid")
    versionName: str = Field(..., title="Versionname")
    isActive: bool = Field(..., title="Isactive")
