# generated by datamodel-codegen:
#   filename:  tts_request.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class TTSRequest(BaseModel):
    text: str = Field(..., max_length=500, min_length=1, title="Text")
    language: str = Field(..., regex="^(en|de|ru|es)$", title="Language")
