# generated by datamodel-codegen:
#   filename:  tts_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class TTSResponse(BaseModel):
    audioData: str = Field(..., title="Audiodata")
    contentType: str | None = Field("audio/mpeg", title="Contenttype")
    text: str = Field(..., title="Text")
    language: str = Field(..., title="Language")
