# generated by datamodel-codegen:
#   filename:  word_list.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class WordListResponse(BaseModel):
    listName: str = Field(..., title='Listname')
    wordCount: int = Field(..., title='Wordcount')
