apiVersion: v2
name: shared-postgres
description: Shared PostgreSQL database for multiple projects
version: 1.0.0
appVersion: "13"
keywords:
  - postgresql
  - database
  - shared
maintainers:
  - name: lingua-quiz-team