# Local Development Values for Shared PostgreSQL
# Usage: helm install shared-postgres ./helm/shared-postgres -f ./helm/shared-postgres/values.local.yaml --create-namespace --namespace shared-database

postgres:
  image:
    repository: postgres
    tag: '13'
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: '256Mi'
      cpu: '100m'
    limits:
      memory: '512Mi'
      cpu: '250m'

  persistence:
    enabled: true
    size: '5Gi'
    storageClass: 'local-path' # Rancher Desktop default. For Docker Desktop, use 'hostpath' or remove this line to use default
    accessMode: 'ReadWriteOnce'

  service:
    type: ClusterIP
    port: 5432

  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999

# Database configuration for local development
# This overrides all databases from values.yaml
databases:
  linguaquiz:
    name: 'linguaquiz_dev'
    user: 'linguaquiz_dev'
    # Remove staging database for local development

# Local development secrets
secrets:
  adminPassword: 'postgres-admin-local'
  databases:
    linguaquiz:
      password: 'linguaquiz-dev-password'

# Disable backup for local development
backup:
  enabled: false

namespace: 'shared-database'
