# generated by datamodel-codegen:
#   filename:  tts_languages.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class TTSLanguagesResponse(BaseModel):
    available: bool = Field(..., title='Available')
    supportedLanguages: list[str] = Field(..., title='Supportedlanguages')
