# generated by datamodel-codegen:
#   filename:  vocabulary_item.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class VocabularyItemResponse(BaseModel):
    id: str = Field(..., title='Id')
    sourceText: str = Field(..., title='Sourcetext')
    sourceLanguage: str = Field(..., title='Sourcelanguage')
    targetText: str = Field(..., title='Targettext')
    targetLanguage: str = Field(..., title='Targetlanguage')
    listName: str = Field(..., title='Listname')
    sourceUsageExample: Optional[str] = Field(..., title='Sourceusageexample')
    targetUsageExample: Optional[str] = Field(..., title='Targetusageexample')
