apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-postgres.fullname" . }}-admin
  namespace: {{ include "shared-postgres.namespace" . }}
  labels:
    {{- include "shared-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  # Master PostgreSQL admin credentials
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "Admin postgres password is required!" .Values.secrets.adminPassword | b64enc | quote }}
---
{{- range $dbName, $dbConfig := .Values.databases }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-postgres.fullname" $ }}-{{ $dbName }}
  namespace: {{ include "shared-postgres.namespace" $ }}
  labels:
    {{- include "shared-postgres.labels" $ | nindent 4 }}
    app.kubernetes.io/database: {{ $dbName }}
type: Opaque
data:
  POSTGRES_DB: {{ $dbConfig.name | b64enc | quote }}
  POSTGRES_USER: {{ $dbConfig.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required (printf "Password for %s database is required!" $dbName) (index $.Values.secrets.databases $dbName "password") | b64enc | quote }}
  # Connection details without password (password should be read from POSTGRES_PASSWORD)
  POSTGRES_HOST: {{ printf "%s.%s.svc.cluster.local" (include "shared-postgres.fullname" $) (include "shared-postgres.namespace" $) | b64enc | quote }}
  POSTGRES_PORT: {{ "5432" | b64enc | quote }}
---
{{- end }}
{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-postgres.fullname" . }}-backup-spaces
  namespace: {{ include "shared-postgres.namespace" . }}
  labels:
    {{- include "shared-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  SPACES_ACCESS_KEY_ID: {{ required "Spaces access key ID is required when backup is enabled!" .Values.backup.spaces.accessKeyId | b64enc | quote }}
  SPACES_SECRET_KEY: {{ required "Spaces secret key is required when backup is enabled!" .Values.backup.spaces.secretKey | b64enc | quote }}
{{- end }}