apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preview-pr-{PR_NUMBER}
resources:
  - helmrelease.yaml
  - image-repository-backend.yaml
  - image-repository-frontend.yaml
  - image-policy-backend.yaml
  - image-policy-frontend.yaml
  - values-secret-encrypted.yaml
