apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingua-quiz-app.frontend.fullname" . }}
  namespace: {{ include "lingua-quiz-app.namespace" . }}
  labels:
    {{- include "lingua-quiz-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lingua-quiz-app.frontend.selectorLabels" . | nindent 4 }}