{{- if .Values.ingress.enabled -}}
{{- $fullName := include "lingua-quiz-app.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "lingua-quiz-app.namespace" . }}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontend.host | quote }}
      http:
        paths:
          # API routes go to backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "lingua-quiz-app.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          # All other routes go to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lingua-quiz-app.frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- if and .Values.ingress.tls .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.frontend.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}