apiVersion: v1
kind: Secret
metadata:
  name: {{include "lingua-quiz-app.fullname" .}}-jwt
  namespace: {{include "lingua-quiz-app.namespace" .}}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4}}
type: Opaque
data:
  # Value must be provided via --set secrets.jwtSecret=YOUR_SECRET
  # Helm automatically base64 encodes values here
  JWT_SECRET: {{required "A JWT secret is required!"
              .Values.secrets.jwtSecret | b64enc | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{include "lingua-quiz-app.fullname" .}}-postgres
  namespace: {{include "lingua-quiz-app.namespace" .}}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4}}
type: Opaque
data:
  # Values must be provided via --set secrets.postgresDb=... etc.
  POSTGRES_DB: {{required "PostgreSQL database name is required!"
                .Values.secrets.postgresDb | b64enc | quote}}
  POSTGRES_USER: {{required "PostgreSQL username is required!"
                  .Values.secrets.postgresUser | b64enc | quote}}
  POSTGRES_PASSWORD: {{required "PostgreSQL password is required!"
                      .Values.secrets.postgresPassword | b64enc | quote}}
{{- if .Values.secrets.googleCloudCredentialsB64}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{include "lingua-quiz-app.fullname" .}}-tts
  namespace: {{include "lingua-quiz-app.namespace" .}}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4}}
type: Opaque
stringData:
  # The Google Cloud credentials are already base64 encoded in the value
  # Use stringData to avoid double encoding
  GOOGLE_CLOUD_CREDENTIALS_B64: {{.Values.secrets.googleCloudCredentialsB64
                                 | quote}}
{{- end}}
