apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingua-quiz-app.fullname" . }}-jwt
  namespace: {{ include "lingua-quiz-app.namespace" . }}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Primary JWT secret for graceful rotation
  {{- if .Values.secrets.jwtPrimarySecret }}
  JWT_PRIMARY_SECRET: {{ .Values.secrets.jwtPrimarySecret | b64enc | quote }}
  {{- else }}
  {{- fail "secrets.jwtPrimarySecret must be provided!" }}
  {{- end }}
  
  # Secondary JWT secret for graceful rotation (optional)
  {{- if .Values.secrets.jwtSecondarySecret }}
  JWT_SECONDARY_SECRET: {{ .Values.secrets.jwtSecondarySecret | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingua-quiz-app.fullname" . }}-postgres
  namespace: {{ include "lingua-quiz-app.namespace" . }}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Values must be provided via --set secrets.postgresDb=... etc.
  POSTGRES_DB: {{ required "PostgreSQL database name is required!" .Values.secrets.postgresDb | b64enc | quote }}
  POSTGRES_USER: {{ required "PostgreSQL username is required!" .Values.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "PostgreSQL password is required!" .Values.secrets.postgresPassword | b64enc | quote }}
{{- if .Values.secrets.googleCloudCredentialsB64 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingua-quiz-app.fullname" . }}-tts
  namespace: {{ include "lingua-quiz-app.namespace" . }}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  # The Google Cloud credentials are already base64 encoded in the value
  # Use stringData to avoid double encoding
  GOOGLE_CLOUD_CREDENTIALS_B64: {{ .Values.secrets.googleCloudCredentialsB64 | quote }}
{{- end }}
{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingua-quiz-app.fullname" . }}-backup-spaces
  namespace: {{ include "lingua-quiz-app.namespace" . }}
  labels:
    {{- include "lingua-quiz-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Values must be provided via --set backup.spaces.accessKeyId=... etc.
  SPACES_ACCESS_KEY_ID: {{ required "Spaces access key ID is required when backup is enabled!" .Values.backup.spaces.accessKeyId | b64enc | quote }}
  SPACES_SECRET_KEY: {{ required "Spaces secret key is required when backup is enabled!" .Values.backup.spaces.secretKey | b64enc | quote }}
{{- end }}
