apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingua-quiz.fullname" . }}
  labels:
    {{- include "lingua-quiz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }} # Expose the service on this port
      targetPort: http # Target the 'http' port name in the deployment
      protocol: TCP
      name: http
  selector:
    {{- include "lingua-quiz.selectorLabels" . | nindent 4 }}