# Example Kubernetes Secret for JWT_SECRET
# This file should be added to infrastructure/gitops/helm-charts/lingua-quiz-app/
# and encrypted with SOPS before committing to git
#
# Usage:
# 1. Generate secret: python3 -c "import secrets; print(secrets.token_urlsafe(64))"
# 2. Update stringData.jwt-secret with generated value
# 3. Encrypt with SOPS: sops -e -i kubernetes-jwt-secret.yaml
# 4. Commit encrypted file to gitops repository
#
# Deployment volume mount configuration (add to deployment.yaml in Helm chart):
#   spec:
#     template:
#       spec:
#         containers:
#         - name: backend
#           volumeMounts:
#           - name: jwt-secret
#             mountPath: /run/secrets
#             readOnly: true
#         volumes:
#         - name: jwt-secret
#           secret:
#             secretName: lingua-quiz-jwt-secret
#             items:
#             - key: jwt-secret
#               path: jwt-secret
#
# Security Best Practices:
# - Never commit unencrypted secrets to git
# - Rotate secrets every 90 days
# - Use different secrets for staging/production
# - For RS256 (recommended for production), generate RSA key pair:
#   ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key
#   openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub

apiVersion: v1
kind: Secret
metadata:
  name: lingua-quiz-jwt-secret
  namespace: lingua-quiz-production  # or lingua-quiz-staging
type: Opaque
stringData:
  jwt-secret: "REPLACE_WITH_STRONG_RANDOM_SECRET"
