apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: frontend
  namespace: preview-pr-219
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^pr-219-[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
