name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/amplify-deploy.yml'
  pull_request:
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/amplify-deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies
      run: npm ci

    - name: Verify npm scripts
      run: |
        # Check if the required build script exists
        if ! npm run | grep -q "build:frontend"; then
          echo "Error: build:frontend script not found in package.json"
          exit 1
        fi

    - name: Build
      run: |
        npm run build:frontend
        if [ $? -ne 0 ]; then
          echo "Error: Build failed"
          exit 1
        fi

    - name: Install jq
      run: sudo apt-get install jq

    - name: Set environment, domain, and branch name
      run: |
        # Set environment variables based on the event type
        if [ "${{ github.event_name }}" == "push" ]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "DOMAIN=${{ secrets.CUSTOM_DOMAIN }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "ENVIRONMENT=preview" >> $GITHUB_ENV
          echo "DOMAIN=${{ secrets.PR_CUSTOM_DOMAIN }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          echo "Unsupported event type: ${{ github.event_name }}"
          exit 1
        fi

    - name: Ensure branch exists in Amplify
      env:
        APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
      run: |
        # Create or update the branch in Amplify
        if ! aws amplify get-branch --app-id $APP_ID --branch-name $BRANCH_NAME &>/dev/null; then
          echo "Branch $BRANCH_NAME does not exist in Amplify. Creating it..."
          aws amplify create-branch --app-id $APP_ID --branch-name $BRANCH_NAME --no-enable-auto-build
        else
          echo "Branch $BRANCH_NAME already exists in Amplify."
        fi

    - name: Deploy to Amplify and wait for completion
      env:
        APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
      run: |
        # Start the deployment job
        JOB_INFO=$(aws amplify start-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-type RELEASE)
        JOB_ID=$(echo $JOB_INFO | jq -r '.jobSummary.jobId')
        echo "Deployment started. Job ID: $JOB_ID"
        
        # Wait for deployment to complete or timeout after 30 minutes
        TIMEOUT=$((30 * 60))
        ELAPSED=0
        while [ $ELAPSED -lt $TIMEOUT ]; do
          STATUS=$(aws amplify get-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-id $JOB_ID --query 'job.summary.status' --output text)
          echo "Current status: $STATUS"
          if [ "$STATUS" == "SUCCEED" ]; then
            echo "Deployment succeeded"
            break
          elif [ "$STATUS" == "FAILED" ]; then
            echo "Deployment failed"
            exit 1
          fi
          sleep 30
          ELAPSED=$((ELAPSED + 30))
        done
        
        if [ $ELAPSED -ge $TIMEOUT ]; then
          echo "Deployment timed out after 30 minutes"
          exit 1
        fi

    - name: Get deployment URL
      env:
        APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
        CUSTOM_DOMAIN_URL: ${{ vars.CUSTOM_DOMAIN_URL }}
        PR_CUSTOM_DOMAIN_URL: ${{ vars.PR_CUSTOM_DOMAIN_URL }}
      run: |
        if [ "$ENVIRONMENT" == "production" ]; then
          DEPLOY_URL="https://${CUSTOM_DOMAIN_URL}"
        else
          DEPLOY_URL="https://${BRANCH_NAME}.${PR_CUSTOM_DOMAIN_URL}"
        fi
        echo "Deployment URL: $DEPLOY_URL"
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV


    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Deployed to: ${process.env.DEPLOY_URL}`
          })

    - name: Create deployment
      id: create_deployment
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          try {
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: '${{ env.ENVIRONMENT }}',
              auto_merge: false,
              required_contexts: [],
              description: 'Deployment via GitHub Actions',
              transient_environment: ${{ env.ENVIRONMENT != 'production' }}
            });
            console.log('Deployment created:', deployment.data);
            return deployment.data.id;
          } catch (error) {
            console.error('Error creating deployment:', error);
            core.setFailed('Failed to create deployment');
            return null;
          }

    - name: Update deployment status
      if: steps.create_deployment.outputs.result
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const deploymentId = ${{ steps.create_deployment.outputs.result }};
          if (deploymentId) {
            try {
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deploymentId,
                state: 'success',
                environment_url: '${{ env.DEPLOY_URL }}',
                description: 'Deployed successfully'
              });
              console.log('Deployment status updated successfully');
            } catch (error) {
              console.error('Error updating deployment status:', error);
            }
          } else {
            console.log('No deployment ID available, skipping status update');
          }
