##
## LinguaQuiz – Copyright © 2025 Nikolay Eremeev
##
## Dual-licensed:
##  – Non-Commercial Source-Available v2  →  see LICENSE-NONCOMMERCIAL.md
##  – Commercial License v2              →  see LICENSE-COMMERCIAL.md
##
## Contact: lingua-quiz@nikolay-eremeev.com
## Repository: https://github.com/nikolay-e/lingua-quiz
##
name: Apply Backup Job to Kubernetes

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

permissions:
  contents: read

jobs:
  apply-backup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kubernetes and Helm Tools
        run: |
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Decode Kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "Kubeconfig set up."

      - name: Verify kubectl configuration
        run: |
          kubectl cluster-info
          kubectl config current-context

      - name: Deploy Backup Job using Helm
        env:
          # Assuming the main production release is named 'lingua-quiz-backend'
          MAIN_APP_RELEASE_NAME: lingua-quiz-backend
          BACKUP_IMAGE_REPO: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/lingua-quiz-backup
          # Use 'latest' tag for backup image or get from build step if available
          BACKUP_IMAGE_TAG: latest
          BACKUP_RELEASE_NAME: lingua-quiz-backup # Helm release name for the backup job
          BACKUP_NAMESPACE: default # Namespace for the backup job
        run: |
          echo "Deploying backup Helm chart to '${BACKUP_NAMESPACE}' namespace..."
          helm uninstall ${BACKUP_RELEASE_NAME} \
            --namespace ${BACKUP_NAMESPACE} && \
          helm upgrade --install ${BACKUP_RELEASE_NAME} ./packages/backend/helm/lingua-quiz-backup \
            --namespace ${BACKUP_NAMESPACE} \
            --create-namespace \
            --set image.repository=${BACKUP_IMAGE_REPO} \
            --set image.tag=${BACKUP_IMAGE_TAG} \
            --set postgresSecretName=${MAIN_APP_RELEASE_NAME}-postgres \
            --set mainAppReleaseName=${MAIN_APP_RELEASE_NAME} \
            --set spaces.accessKeyId=${{ secrets.DO_SPACES_ACCESS_KEY_ID }} \
            --set spaces.secretKey=${{ secrets.DO_SPACES_SECRET_KEY }} \
            # Add other values like schedule if needed, otherwise defaults are used
            # --set schedule="0 3 * * *"
          echo "Helm upgrade command executed."

      - name: Verify CronJob Creation
        env:
          BACKUP_RELEASE_NAME: lingua-quiz-backup # Must match the release name used above
          BACKUP_NAMESPACE: default # Must match the namespace used above
        run: |
          echo "Verifying CronJob status..."
          # Check Helm-managed resources
          kubectl get secret ${BACKUP_RELEASE_NAME}-spaces-credentials -n ${BACKUP_NAMESPACE}
          kubectl get cronjob ${BACKUP_RELEASE_NAME} -n ${BACKUP_NAMESPACE} -o wide
          echo "Verification complete."
