name: Run Backend Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        cd packages/backend
        npm ci

    - name: Determine API URL and Run tests
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          API_URL="https://test-api.lingua-quiz.nikolay-eremeev.com:443"
        else
          API_URL="https://api.lingua-quiz.nikolay-eremeev.com:443"
        fi
        
        cd packages/backend
        npm install --save-dev @babel/core @babel/preset-env babel-jest
        API_URL=$API_URL CA_CERT="${{ secrets.TLS_CA_CRT }}" npm test
  
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: packages/backend/test-results