name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    # Add permissions to write to GHCR
    permissions:
      contents: read
      packages: write # Grant permission to push to GitHub Packages (GHCR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for secure auth

      # Build and push backend image with cache
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: backend
          push: true
          tags: ghcr.io/${{ github.repository }}/lingua-quiz-backend:${{ github.event.pull_request.head.sha || github.sha }}
          # This is the key for caching - use sanitized ref name to avoid invalid characters
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/lingua-quiz-backend:${{ github.event.pull_request.number || github.ref_name }}-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/lingua-quiz-backend:${{ github.event.pull_request.number || github.ref_name }}-cache,mode=max

      # Build and push frontend image with cache
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/lingua-quiz-frontend:${{ github.event.pull_request.head.sha || github.sha }}
          # This is the key for caching - use sanitized ref name to avoid invalid characters
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/lingua-quiz-frontend:${{ github.event.pull_request.number || github.ref_name }}-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/lingua-quiz-frontend:${{ github.event.pull_request.number || github.ref_name }}-cache,mode=max

      # Build and push integration tests image with cache
      - name: Build and push integration tests image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: integration-e2e-tests
          push: true
          tags: ghcr.io/${{ github.repository }}/lingua-quiz-integration-e2e-tests:${{ github.event.pull_request.head.sha || github.sha }}
          # This is the key for caching - use sanitized ref name to avoid invalid characters
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/lingua-quiz-integration-e2e-tests:${{ github.event.pull_request.number || github.ref_name }}-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/lingua-quiz-integration-e2e-tests:${{ github.event.pull_request.number || github.ref_name }}-cache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'
    environment: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    permissions:
      contents: read
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.4' # Pin to specific version

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0' # Pin to specific version

      # Setup SOPS
      - name: Setup SOPS
        uses: mdgreenwald/mozilla-sops-action@v1.6.0
        with:
          version: '3.10.2' # Pin to specific version

      # Set environment name for deployment (production for main, staging for PRs)
      - name: Set deployment environment
        id: env
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "env_name=staging" >> $GITHUB_OUTPUT
            echo "namespace=lingua-quiz-staging" >> $GITHUB_OUTPUT
          else
            echo "env_name=prod" >> $GITHUB_OUTPUT
            echo "namespace=lingua-quiz-production" >> $GITHUB_OUTPUT
          fi

      # Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          cat << 'EOF' > $HOME/.kube/config
          ${{ secrets.KUBE_CONFIG }}
          EOF
          chmod 600 $HOME/.kube/config

      # Setup SOPS with age key
      - name: Setup SOPS with age key
        run: |
          echo "${{ secrets.AGE_PRIVATE_KEY }}" > .age-key.txt
          chmod 600 .age-key.txt

      # Create GHCR secret in target namespace
      - name: Create GHCR secret
        run: |
          NAMESPACE="${{ steps.env.outputs.namespace }}"
          echo "Creating GHCR secret in namespace: $NAMESPACE"

          # Create namespace if it doesn't exist
          kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

          # Delete existing secret if it exists (to update credentials)
          kubectl delete secret ghcr-secret -n "$NAMESPACE" || true

          # Create new GHCR secret
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.repository_owner }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --docker-email=noreply@github.com \
            -n "$NAMESPACE"

      # Deploy with Makefile, now using GHCR images
      - name: Deploy with Makefile
        id: helm-deploy
        run: |
          IMAGE_TAG="${{ github.event.pull_request.head.sha || github.sha }}"
          ENV_NAME="${{ steps.env.outputs.env_name }}"

          echo "Deploying to $ENV_NAME environment with image tag: $IMAGE_TAG"

          # Debug: Show current releases
          echo "Listing all Helm releases:"
          helm list -A || true

          # Validate chart before installation
          echo "Validating Helm chart..."
          helm lint ./helm/lingua-quiz-app

          # Deploy using Makefile with GHCR registry (no clean to avoid downtime)
          echo "Deploying to $ENV_NAME..."
          make deploy ENV=$ENV_NAME IMAGE_TAG="$IMAGE_TAG" REGISTRY="ghcr.io/${{ github.repository }}"

      # Wait for test jobs to complete and check their status
      - name: Wait for and validate test jobs
        if: steps.env.outputs.env_name == 'staging'
        run: |
          NAMESPACE="${{ steps.env.outputs.namespace }}"
          echo "Waiting for test jobs to complete in namespace: $NAMESPACE"

          # Wait for test job to appear
          echo "Waiting for test job to be created..."
          timeout 300 bash -c 'while ! kubectl get job lingua-quiz-tests -n '"$NAMESPACE"' 2>/dev/null; do sleep 5; done' || {
            echo "Test job was not created within 5 minutes"
            exit 1
          }

          # Wait for test job to complete (success or failure)
          echo "Waiting for test job to complete..."
          timeout 600 bash -c 'while [[ $(kubectl get job lingua-quiz-tests -n '"$NAMESPACE"' -o jsonpath="{.status.conditions[?(@.type==\"Complete\")].status}" 2>/dev/null) != "True" ]] && [[ $(kubectl get job lingua-quiz-tests -n '"$NAMESPACE"' -o jsonpath="{.status.conditions[?(@.type==\"Failed\")].status}" 2>/dev/null) != "True" ]]; do sleep 10; done' || {
            echo "Test job did not complete within 10 minutes"
            kubectl describe job lingua-quiz-tests -n "$NAMESPACE"
            kubectl logs job/lingua-quiz-tests -n "$NAMESPACE" --tail=100 || true
            exit 1
          }

          # Check if test job succeeded
          if [[ $(kubectl get job lingua-quiz-tests -n "$NAMESPACE" -o jsonpath="{.status.conditions[?(@.type==\"Complete\")].status}" 2>/dev/null) == "True" ]]; then
            echo "✅ Test job completed successfully"
            kubectl logs job/lingua-quiz-tests -n "$NAMESPACE" --tail=50
          else
            echo "❌ Test job failed"
            kubectl describe job lingua-quiz-tests -n "$NAMESPACE"
            kubectl logs job/lingua-quiz-tests -n "$NAMESPACE" --tail=100 || true
            exit 1
          fi
