name: Common Tests

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  depcheck:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run depcheck
        run: npm run depcheck

      - name: Log results
        run: |
          echo "::group::Depcheck Results"
          echo "Depcheck completed. Check above for detailed results."
          echo "::endgroup::"

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Log results
        run: |
          echo "::group::ESLint Results"
          echo "ESLint completed. Check above for detailed results."
          echo "::endgroup::"

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --workspace=@linguaquiz/frontend

      - name: Log results
        run: |
          echo "::group::Frontend Test Results"
          echo "Frontend tests completed. Check above for detailed results."
          echo "::endgroup::"
