name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Auto-merge Minor/Patch Updates
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Check PR labels
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(l => l.name);

            // Проверяем что это minor/patch обновление
            const title = pr.title.toLowerCase();
            const isMinorOrPatch =
              title.includes('minor') ||
              title.includes('patch') ||
              title.match(/bump .* from .* to .*/);

            const isMajor = title.includes('major');

            // Автомерж только для minor/patch, не для major
            const shouldAutomerge = isMinorOrPatch && !isMajor && labels.includes('dependencies');

            core.setOutput('automerge', shouldAutomerge);

            if (shouldAutomerge) {
              console.log(`✓ Will auto-merge: ${pr.title}`);
            } else {
              console.log(`✗ Skip auto-merge: ${pr.title} (major update or not dependencies)`);
            }

      - name: Enable auto-merge
        if: steps.check.outputs.automerge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            // Use GitHub's native auto-merge feature
            // This will automatically merge once all required checks pass
            try {
              await github.rest.pulls.createAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });

              console.log(`✓ Auto-merge enabled for PR #${pr.number}`);
              console.log('  PR will merge automatically once all checks pass');
            } catch (error) {
              // Auto-merge might already be enabled or repo doesn't support it
              if (error.status === 422) {
                console.log('Auto-merge already enabled or not available');
              } else {
                throw error;
              }
            }
