##
## LinguaQuiz – Copyright © 2025 Nikolay Eremeev
##
## Dual-licensed:
##  – Non-Commercial Source-Available v2  →  see LICENSE-NONCOMMERCIAL.md
##  – Commercial License v2              →  see LICENSE-COMMERCIAL.md
##
## Contact: lingua-quiz@nikolay-eremeev.com
## Repository: https://github.com/nikolay-e/lingua-quiz
##
name: PR Review

on:
  pull_request:
    types:
      - ready_for_review

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write
  security-events: write

jobs:
  ai-review:
    if: github.event.pull_request.draft == false
    uses: nikolay-e/reusable-workflows/.github/workflows/reusable-ai-review.yml@main
    secrets: inherit
