name: Security Scans

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: "Frontend"
            url: "https://lingua-quiz.nikolay-eremeev.com"
          - name: "Backend-API"
            url: "https://lingua-quiz.nikolay-eremeev.com/api"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan - ${{ matrix.target.name }}
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ matrix.target.url }}
          fail_action: false
          cmd_options: '-a -j -m 10 -T 120'
          artifact_name: 'zap-${{ matrix.target.name }}-report'

      - name: Upload ZAP results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-${{ matrix.target.name }}-results
          path: |
            report_html.html
            report_json.json
            report_md.md

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'LinguaQuiz'
          path: '.'
          format: 'ALL'
          args: >
            --enableRetired
            --enableExperimental

      - name: Upload dependency check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/
