name: Security Scans

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  zap-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan (Frontend)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://lingua-quiz.nikolay-eremeev.com'
          fail_action: false

      - name: Run ZAP Baseline Scan (Backend API)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://api-lingua-quiz.nikolay-eremeev.com'
          fail_action: false