##
## LinguaQuiz – Copyright © 2025 Nikolay Eremeev
##
## Dual-licensed:
##  – Non-Commercial Source-Available v2  →  see LICENSE-NONCOMMERCIAL.md
##  – Commercial License v2              →  see LICENSE-COMMERCIAL.md
##
## Contact: lingua-quiz@nikolay-eremeev.com
## Repository: https://github.com/nikolay-e/lingua-quiz
##
name: Integration Tests

on:
  workflow_call:
    inputs:
      frontend-url:
        required: false
        type: string
        default: ""
      backend-url:
        required: false
        type: string
        default: ""

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  zap-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set ZAP Scan Target URLs
        run: |
          # Use input URLs if provided, otherwise determine dynamically
          if [[ -n "${{ inputs.frontend-url }}" ]]; then
            echo "ZAP_FRONTEND_URL=${{ inputs.frontend-url }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "ZAP_FRONTEND_URL=https://test-lingua-quiz.nikolay-eremeev.com" >> $GITHUB_ENV
          else
            echo "ZAP_FRONTEND_URL=https://lingua-quiz.nikolay-eremeev.com" >> $GITHUB_ENV
          fi

          if [[ -n "${{ inputs.backend-url }}" ]]; then
            echo "ZAP_BACKEND_URL=${{ inputs.backend-url }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "ZAP_BACKEND_URL=https://test-api-lingua-quiz.nikolay-eremeev.com" >> $GITHUB_ENV
          else
            echo "ZAP_BACKEND_URL=https://api-lingua-quiz.nikolay-eremeev.com" >> $GITHUB_ENV
          fi

      - name: Run ZAP Full Scan (Frontend)
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.ZAP_FRONTEND_URL }}
          cmd_options: "-a"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          rules_file_name: ".zap/rules.tsv"
          allow_issue_writing: true
          issue_title: "ZAP Security Scan Report (Frontend)"
          fail_action: false
          artifact_name: "zap_frontend_scan_report"

      - name: Run ZAP Full Scan (Backend API)
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.ZAP_BACKEND_URL }}
          cmd_options: "-a"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          rules_file_name: ".zap/api-rules.tsv"
          allow_issue_writing: true
          issue_title: "ZAP Security Scan Report (API)"
          fail_action: false
          artifact_name: "zap_backend_scan_report"

      - name: Combine and Upload Reports
        run: |
          mkdir -p zap-reports
          mv */report_html.html zap-frontend-report.html || true
          mv */report_html.html zap-backend-report.html || true
          mv zap-*-report.html zap-reports/ || true
          ls -la zap-reports || echo "No reports found"

      - name: Upload ZAP Scan Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_reports
          path: zap-reports
